//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISD.Client.Model.Resources
{
    using System;


    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISD.Client.Model.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add OU ähnelt.
        /// </summary>
        public static string AddOU
        {
            get
            {
                return ResourceManager.GetString("AddOU", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administration ähnelt.
        /// </summary>
        public static string Administration
        {
            get
            {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MISD ähnelt.
        /// </summary>
        public static string ApplicationTitle
        {
            get
            {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available email adresses: ähnelt.
        /// </summary>
        public static string AvailableEMails
        {
            get
            {
                return ResourceManager.GetString("AvailableEMails", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 Chars ähnelt.
        /// </summary>
        public static string CharFormat
        {
            get
            {
                return ResourceManager.GetString("CharFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are running an operator instance of MISD OWL. Do you want to close the powerwall, too? ähnelt.
        /// </summary>
        public static string ClosePowerwallText
        {
            get
            {
                return ResourceManager.GetString("ClosePowerwallText", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close all powerwall instances? ähnelt.
        /// </summary>
        public static string ClosePowerwallTitle
        {
            get
            {
                return ResourceManager.GetString("ClosePowerwallTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save the current Layout before closing? ähnelt.
        /// </summary>
        public static string CloseText
        {
            get
            {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close Dialog ähnelt.
        /// </summary>
        public static string CloseTitel
        {
            get
            {
                return ResourceManager.GetString("CloseTitel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cluster ähnelt.
        /// </summary>
        public static string Cluster
        {
            get
            {
                return ResourceManager.GetString("Cluster", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color Scheme ähnelt.
        /// </summary>
        public static string ColorScheme
        {
            get
            {
                return ResourceManager.GetString("ColorScheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please make sure that you are connected to the network. ähnelt.
        /// </summary>
        public static string ConnectionErrorSubtitle
        {
            get
            {
                return ResourceManager.GetString("ConnectionErrorSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not connect to the server! ähnelt.
        /// </summary>
        public static string ConnectionErrorTitle
        {
            get
            {
                return ResourceManager.GetString("ConnectionErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Critical ähnelt.
        /// </summary>
        public static string Critical
        {
            get
            {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daily Mail Report: ähnelt.
        /// </summary>
        public static string DailyMail
        {
            get
            {
                return ResourceManager.GetString("DailyMail", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 Days ähnelt.
        /// </summary>
        public static string DaysFormat
        {
            get
            {
                return ResourceManager.GetString("DaysFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string Details
        {
            get
            {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail ähnelt.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available Organisation Units ähnelt.
        /// </summary>
        public static string ExistOU
        {
            get
            {
                return ResourceManager.GetString("ExistOU", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string Exit
        {
            get
            {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        public static string Filter
        {
            get
            {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font: ähnelt.
        /// </summary>
        public static string Font
        {
            get
            {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font Size: ähnelt.
        /// </summary>
        public static string FontSize
        {
            get
            {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gallery ähnelt.
        /// </summary>
        public static string Gallery
        {
            get
            {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generated ähnelt.
        /// </summary>
        public static string Generated
        {
            get
            {
                return ResourceManager.GetString("Generated", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Known Clusters ähnelt.
        /// </summary>
        public static string GivenClusters
        {
            get
            {
                return ResourceManager.GetString("GivenClusters", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignored ähnelt.
        /// </summary>
        public static string Ignored
        {
            get
            {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignored monitored systemes ähnelt.
        /// </summary>
        public static string IgnoreList
        {
            get
            {
                return ResourceManager.GetString("IgnoreList", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Indicator ähnelt.
        /// </summary>
        public static string Indicator
        {
            get
            {
                return ResourceManager.GetString("Indicator", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string Info
        {
            get
            {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait while initial synchroniatzon of client data. ähnelt.
        /// </summary>
        public static string InitSyncSubtitle
        {
            get
            {
                return ResourceManager.GetString("InitSyncSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initial Synchronization... ähnelt.
        /// </summary>
        public static string InitSyncTitle
        {
            get
            {
                return ResourceManager.GetString("InitSyncTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intervalls ähnelt.
        /// </summary>
        public static string Intervalls
        {
            get
            {
                return ResourceManager.GetString("Intervalls", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Changed ähnelt.
        /// </summary>
        public static string LastChanged
        {
            get
            {
                return ResourceManager.GetString("LastChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layout ähnelt.
        /// </summary>
        public static string Layout
        {
            get
            {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of layout ähnelt.
        /// </summary>
        public static string LayoutName
        {
            get
            {
                return ResourceManager.GetString("LayoutName", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Level ähnelt.
        /// </summary>
        public static string Level
        {
            get
            {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Levels ähnelt.
        /// </summary>
        public static string Levels
        {
            get
            {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail Settings ähnelt.
        /// </summary>
        public static string MailSettings
        {
            get
            {
                return ResourceManager.GetString("MailSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail Warning ähnelt.
        /// </summary>
        public static string MailWarning
        {
            get
            {
                return ResourceManager.GetString("MailWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main Update Interval ähnelt.
        /// </summary>
        public static string MainInterval
        {
            get
            {
                return ResourceManager.GetString("MainInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maintenance ähnelt.
        /// </summary>
        public static string Maintenance
        {
            get
            {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mapping ähnelt.
        /// </summary>
        public static string Mapping
        {
            get
            {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metric Critical ähnelt.
        /// </summary>
        public static string MetricCritical
        {
            get
            {
                return ResourceManager.GetString("MetricCritical", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metric Warning ähnelt.
        /// </summary>
        public static string MetricWarning
        {
            get
            {
                return ResourceManager.GetString("MetricWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitored-System-Intervall: ähnelt.
        /// </summary>
        public static string MonitoredSystemIntervall
        {
            get
            {
                return ResourceManager.GetString("MonitoredSystemIntervall", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitored Systems ähnelt.
        /// </summary>
        public static string MonitoredSystems
        {
            get
            {
                return ResourceManager.GetString("MonitoredSystems", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitoring ähnelt.
        /// </summary>
        public static string Monitoring
        {
            get
            {
                return ResourceManager.GetString("Monitoring", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string New
        {
            get
            {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Name ähnelt.
        /// </summary>
        public static string NewName
        {
            get
            {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No change yet ähnelt.
        /// </summary>
        public static string NoChangeYet
        {
            get
            {
                return ResourceManager.GetString("NoChangeYet", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        /// </summary>
        public static string Normal
        {
            get
            {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No single selection ähnelt.
        /// </summary>
        public static string NoSingleSelection
        {
            get
            {
                return ResourceManager.GetString("NoSingleSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Ignored ähnelt.
        /// </summary>
        public static string NotIgnored
        {
            get
            {
                return ResourceManager.GetString("NotIgnored", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not registerd ähnelt.
        /// </summary>
        public static string NotRegisterd
        {
            get
            {
                return ResourceManager.GetString("NotRegisterd", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of Layouts ähnelt.
        /// </summary>
        public static string NumberLayouts
        {
            get
            {
                return ResourceManager.GetString("NumberLayouts", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum of characters of a name: ähnelt.
        /// </summary>
        public static string NumberOfChar
        {
            get
            {
                return ResourceManager.GetString("NumberOfChar", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chosen Systems ähnelt.
        /// </summary>
        public static string NumberOfChosenSystems
        {
            get
            {
                return ResourceManager.GetString("NumberOfChosenSystems", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of indicators ähnelt.
        /// </summary>
        public static string NumberOfRows
        {
            get
            {
                return ResourceManager.GetString("NumberOfRows", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string OK
        {
            get
            {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string Options
        {
            get
            {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options-Intervall: ähnelt.
        /// </summary>
        public static string OptionsIntervall
        {
            get
            {
                return ResourceManager.GetString("OptionsIntervall", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Organizational Units ähnelt.
        /// </summary>
        public static string OUs
        {
            get
            {
                return ResourceManager.GetString("OUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path ähnelt.
        /// </summary>
        public static string Path
        {
            get
            {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin ähnelt.
        /// </summary>
        public static string Plugin
        {
            get
            {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin-Intervall: ähnelt.
        /// </summary>
        public static string PluginIntervall
        {
            get
            {
                return ResourceManager.GetString("PluginIntervall", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin Priority ähnelt.
        /// </summary>
        public static string PrioPlugins
        {
            get
            {
                return ResourceManager.GetString("PrioPlugins", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string Refresh
        {
            get
            {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regular Expression ähnelt.
        /// </summary>
        public static string RegEX
        {
            get
            {
                return ResourceManager.GetString("RegEX", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registerd ähnelt.
        /// </summary>
        public static string Registerd
        {
            get
            {
                return ResourceManager.GetString("Registerd", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename ähnelt.
        /// </summary>
        public static string Rename
        {
            get
            {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected Items: ähnelt.
        /// </summary>
        public static string Selected
        {
            get
            {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings
        {
            get
            {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set to maintenance ähnelt.
        /// </summary>
        public static string SetToMaintenance
        {
            get
            {
                return ResourceManager.GetString("SetToMaintenance", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show tile statusbar ähnelt.
        /// </summary>
        public static string ShowTileStatusBar
        {
            get
            {
                return ResourceManager.GetString("ShowTileStatusBar", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string Status
        {
            get
            {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop maintenace mode ähnelt.
        /// </summary>
        public static string StopMaintenance
        {
            get
            {
                return ResourceManager.GetString("StopMaintenance", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storage Duration ähnelt.
        /// </summary>
        public static string StorageDuration
        {
            get
            {
                return ResourceManager.GetString("StorageDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Systems in OU ähnelt.
        /// </summary>
        public static string SystemsInOU
        {
            get
            {
                return ResourceManager.GetString("SystemsInOU", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Style ähnelt.
        /// </summary>
        public static string TextStyle
        {
            get
            {
                return ResourceManager.GetString("TextStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tiles ähnelt.
        /// </summary>
        public static string Tiles
        {
            get
            {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total ähnelt.
        /// </summary>
        public static string Total
        {
            get
            {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string Type
        {
            get
            {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        public static string Update
        {
            get
            {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use CustomUI ähnelt.
        /// </summary>
        public static string UseCustomUI
        {
            get
            {
                return ResourceManager.GetString("UseCustomUI", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        public static string User
        {
            get
            {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        public static string View
        {
            get
            {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string Warning
        {
            get
            {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
