//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISD.Test.Workstation.Linux.WSWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PluginMetadata", Namespace="http://schemas.datacontract.org/2004/07/MISD.Core")]
    [System.SerializableAttribute()]
    public partial class PluginMetadata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyrightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MISD.Test.Workstation.Linux.WSWebService.IndicatorSettings[] IndicatorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Version VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Copyright {
            get {
                return this.CopyrightField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyrightField, value) != true)) {
                    this.CopyrightField = value;
                    this.RaisePropertyChanged("Copyright");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MISD.Test.Workstation.Linux.WSWebService.IndicatorSettings[] Indicators {
            get {
                return this.IndicatorsField;
            }
            set {
                if ((object.ReferenceEquals(this.IndicatorsField, value) != true)) {
                    this.IndicatorsField = value;
                    this.RaisePropertyChanged("Indicators");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Version Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndicatorSettings", Namespace="http://schemas.datacontract.org/2004/07/MISD.Core")]
    [System.SerializableAttribute()]
    public partial class IndicatorSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MISD.Test.Workstation.Linux.WSWebService.DataType DataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilterStatementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndicatorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan MappingDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetricCriticalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetricWarningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PluginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan StorageDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan UpdateIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkstationDomainNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MISD.Test.Workstation.Linux.WSWebService.DataType DataType {
            get {
                return this.DataTypeField;
            }
            set {
                if ((this.DataTypeField.Equals(value) != true)) {
                    this.DataTypeField = value;
                    this.RaisePropertyChanged("DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilterStatement {
            get {
                return this.FilterStatementField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterStatementField, value) != true)) {
                    this.FilterStatementField = value;
                    this.RaisePropertyChanged("FilterStatement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndicatorName {
            get {
                return this.IndicatorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IndicatorNameField, value) != true)) {
                    this.IndicatorNameField = value;
                    this.RaisePropertyChanged("IndicatorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan MappingDuration {
            get {
                return this.MappingDurationField;
            }
            set {
                if ((this.MappingDurationField.Equals(value) != true)) {
                    this.MappingDurationField = value;
                    this.RaisePropertyChanged("MappingDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetricCritical {
            get {
                return this.MetricCriticalField;
            }
            set {
                if ((object.ReferenceEquals(this.MetricCriticalField, value) != true)) {
                    this.MetricCriticalField = value;
                    this.RaisePropertyChanged("MetricCritical");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetricWarning {
            get {
                return this.MetricWarningField;
            }
            set {
                if ((object.ReferenceEquals(this.MetricWarningField, value) != true)) {
                    this.MetricWarningField = value;
                    this.RaisePropertyChanged("MetricWarning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PluginName {
            get {
                return this.PluginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PluginNameField, value) != true)) {
                    this.PluginNameField = value;
                    this.RaisePropertyChanged("PluginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan StorageDuration {
            get {
                return this.StorageDurationField;
            }
            set {
                if ((this.StorageDurationField.Equals(value) != true)) {
                    this.StorageDurationField = value;
                    this.RaisePropertyChanged("StorageDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan UpdateInterval {
            get {
                return this.UpdateIntervalField;
            }
            set {
                if ((this.UpdateIntervalField.Equals(value) != true)) {
                    this.UpdateIntervalField = value;
                    this.RaisePropertyChanged("UpdateInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkstationDomainName {
            get {
                return this.WorkstationDomainNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkstationDomainNameField, value) != true)) {
                    this.WorkstationDomainNameField = value;
                    this.RaisePropertyChanged("WorkstationDomainName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType", Namespace="http://schemas.datacontract.org/2004/07/MISD.Core")]
    public enum DataType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Float = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Byte = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PluginFile", Namespace="http://schemas.datacontract.org/2004/07/MISD.Core")]
    [System.SerializableAttribute()]
    public partial class PluginFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileAsBase64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileAsBase64 {
            get {
                return this.FileAsBase64Field;
            }
            set {
                if ((object.ReferenceEquals(this.FileAsBase64Field, value) != true)) {
                    this.FileAsBase64Field = value;
                    this.RaisePropertyChanged("FileAsBase64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogType", Namespace="http://schemas.datacontract.org/2004/07/MISD.Core")]
    public enum LogType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debug = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSWebService.IWorkstationWebService")]
    public interface IWorkstationWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkstationWebService/GetMainUpdateInterval", ReplyAction="http://tempuri.org/IWorkstationWebService/GetMainUpdateIntervalResponse")]
        System.TimeSpan GetMainUpdateInterval();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkstationWebService/SignIn", ReplyAction="http://tempuri.org/IWorkstationWebService/SignInResponse")]
        bool SignIn(string workstationName, byte operatingSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkstationWebService/SignOut", ReplyAction="http://tempuri.org/IWorkstationWebService/SignOutResponse")]
        bool SignOut(string workstationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkstationWebService/GetPluginList", ReplyAction="http://tempuri.org/IWorkstationWebService/GetPluginListResponse")]
        MISD.Test.Workstation.Linux.WSWebService.PluginMetadata[] GetPluginList(string workstationDomainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkstationWebService/DownloadPlugins", ReplyAction="http://tempuri.org/IWorkstationWebService/DownloadPluginsResponse")]
        MISD.Test.Workstation.Linux.WSWebService.PluginFile[] DownloadPlugins(string workstationDomainName, string[] pluginNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkstationWebService/UploadIndicatorValues", ReplyAction="http://tempuri.org/IWorkstationWebService/UploadIndicatorValuesResponse")]
        bool UploadIndicatorValues(string workstationDomainName, string pluginName, System.Tuple<string, object, MISD.Test.Workstation.Linux.WSWebService.DataType, System.DateTime>[] indicatorValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkstationWebService/UploadIndicatorValue", ReplyAction="http://tempuri.org/IWorkstationWebService/UploadIndicatorValueResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Version))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Tuple<string, object, MISD.Test.Workstation.Linux.WSWebService.DataType, System.DateTime>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Tuple<string, object, MISD.Test.Workstation.Linux.WSWebService.DataType, System.DateTime>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Tuple<string, string>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Tuple<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Tuple<string, System.Nullable<long>>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Tuple<string, System.Nullable<long>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MISD.Test.Workstation.Linux.WSWebService.PluginMetadata[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MISD.Test.Workstation.Linux.WSWebService.PluginMetadata))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MISD.Test.Workstation.Linux.WSWebService.IndicatorSettings[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MISD.Test.Workstation.Linux.WSWebService.IndicatorSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MISD.Test.Workstation.Linux.WSWebService.DataType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MISD.Test.Workstation.Linux.WSWebService.PluginFile[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MISD.Test.Workstation.Linux.WSWebService.PluginFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MISD.Test.Workstation.Linux.WSWebService.LogType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        bool UploadIndicatorValue(string workstationDomainName, string pluginName, string indicatorValueName, object value, MISD.Test.Workstation.Linux.WSWebService.DataType valueDataType, System.DateTime aquiredTimestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkstationWebService/GetFilters", ReplyAction="http://tempuri.org/IWorkstationWebService/GetFiltersResponse")]
        System.Tuple<string, string>[] GetFilters(string workstationDomainName, string pluginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkstationWebService/GetFilter", ReplyAction="http://tempuri.org/IWorkstationWebService/GetFilterResponse")]
        string GetFilter(string workstationDomainName, string pluginName, string indicatorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkstationWebService/GetUpdateIntervals", ReplyAction="http://tempuri.org/IWorkstationWebService/GetUpdateIntervalsResponse")]
        System.Tuple<string, System.Nullable<long>>[] GetUpdateIntervals(string workstationDomainName, string pluginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkstationWebService/GetUpdateInterval", ReplyAction="http://tempuri.org/IWorkstationWebService/GetUpdateIntervalResponse")]
        long GetUpdateInterval(string workstationDomainName, string pluginName, string indicatorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkstationWebService/WriteLog", ReplyAction="http://tempuri.org/IWorkstationWebService/WriteLogResponse")]
        void WriteLog(string message, MISD.Test.Workstation.Linux.WSWebService.LogType type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkstationWebServiceChannel : MISD.Test.Workstation.Linux.WSWebService.IWorkstationWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkstationWebServiceClient : System.ServiceModel.ClientBase<MISD.Test.Workstation.Linux.WSWebService.IWorkstationWebService>, MISD.Test.Workstation.Linux.WSWebService.IWorkstationWebService {
        
        public WorkstationWebServiceClient() {
        }
        
        public WorkstationWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkstationWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkstationWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkstationWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.TimeSpan GetMainUpdateInterval() {
            return base.Channel.GetMainUpdateInterval();
        }
        
        public bool SignIn(string workstationName, byte operatingSystem) {
            return base.Channel.SignIn(workstationName, operatingSystem);
        }
        
        public bool SignOut(string workstationName) {
            return base.Channel.SignOut(workstationName);
        }
        
        public MISD.Test.Workstation.Linux.WSWebService.PluginMetadata[] GetPluginList(string workstationDomainName) {
            return base.Channel.GetPluginList(workstationDomainName);
        }
        
        public MISD.Test.Workstation.Linux.WSWebService.PluginFile[] DownloadPlugins(string workstationDomainName, string[] pluginNames) {
            return base.Channel.DownloadPlugins(workstationDomainName, pluginNames);
        }
        
        public bool UploadIndicatorValues(string workstationDomainName, string pluginName, System.Tuple<string, object, MISD.Test.Workstation.Linux.WSWebService.DataType, System.DateTime>[] indicatorValues) {
            return base.Channel.UploadIndicatorValues(workstationDomainName, pluginName, indicatorValues);
        }
        
        public bool UploadIndicatorValue(string workstationDomainName, string pluginName, string indicatorValueName, object value, MISD.Test.Workstation.Linux.WSWebService.DataType valueDataType, System.DateTime aquiredTimestamp) {
            return base.Channel.UploadIndicatorValue(workstationDomainName, pluginName, indicatorValueName, value, valueDataType, aquiredTimestamp);
        }
        
        public System.Tuple<string, string>[] GetFilters(string workstationDomainName, string pluginName) {
            return base.Channel.GetFilters(workstationDomainName, pluginName);
        }
        
        public string GetFilter(string workstationDomainName, string pluginName, string indicatorName) {
            return base.Channel.GetFilter(workstationDomainName, pluginName, indicatorName);
        }
        
        public System.Tuple<string, System.Nullable<long>>[] GetUpdateIntervals(string workstationDomainName, string pluginName) {
            return base.Channel.GetUpdateIntervals(workstationDomainName, pluginName);
        }
        
        public long GetUpdateInterval(string workstationDomainName, string pluginName, string indicatorName) {
            return base.Channel.GetUpdateInterval(workstationDomainName, pluginName, indicatorName);
        }
        
        public void WriteLog(string message, MISD.Test.Workstation.Linux.WSWebService.LogType type) {
            base.Channel.WriteLog(message, type);
        }
    }
}
